name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh/
          
          # Write the private key to file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key
          
          # Set correct permissions (very important!)
          chmod 600 ~/.ssh/deploy-key
          chmod 700 ~/.ssh/
          
          # Add the host to known_hosts to avoid host key verification
          ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts 2>/dev/null
          
          # Create SSH config
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key
            StrictHostKeyChecking no
            UserKnownHostsFile ~/.ssh/known_hosts
            IdentitiesOnly yes
          END
          
          # Set permissions for SSH config
          chmod 600 ~/.ssh/config
          
          # Debug: Check SSH key format and fingerprint
          echo "SSH key format check:"
          head -n 1 ~/.ssh/deploy-key
          tail -n 1 ~/.ssh/deploy-key
          echo "Key fingerprint:"
          ssh-keygen -l -f ~/.ssh/deploy-key 2>/dev/null || echo "Could not generate fingerprint"
          
          # Debug: Test SSH connection with verbose output
          echo "Testing SSH connection..."
          ssh -v -o ConnectTimeout=10 -o BatchMode=yes my-vps 'echo "SSH connection successful"' 2>&1 || echo "SSH connection failed"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Deploy to VPS
        run: |
          echo "Deploying to project directory: ${{ secrets.PROJECT_ROOT }}"
          ssh my-vps "cd ${{ secrets.PROJECT_ROOT }} && pwd && ls -la"
          
          # You can add more deployment commands here, for example:
          # ssh my-vps "cd ${{ secrets.PROJECT_ROOT }} && git pull origin main"
          # ssh my-vps "cd ${{ secrets.PROJECT_ROOT }} && pip install -r requirements.txt"
          # ssh my-vps "cd ${{ secrets.PROJECT_ROOT }} && sudo systemctl restart your-app-service"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
