name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    
    # Define environment variables for the entire job
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_IP: ${{ secrets.SSH_IP }}
      PROJECT_ROOT: ${{ secrets.PROJECT_ROOT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh/
          
          # Write the private key to file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key
          
          # Set correct permissions (very important!)
          chmod 600 ~/.ssh/deploy-key
          
          # Add the host to known_hosts to avoid host key verification
          ssh-keyscan -H "$SSH_IP" >> ~/.ssh/known_hosts
          
          # Create SSH config to use a convenient alias
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key
            IdentitiesOnly yes
          END
          
          # Set permissions for SSH config
          chmod 600 ~/.ssh/config

      - name: Deploy and run redeployment script
        run: |
          echo "Connecting to VPS and executing redeploy-site.sh..."
          ssh my-vps "bash ${{ secrets.PROJECT_ROOT }}/redeploy-site.sh"

